server_port: 3475 # BATS

coffee:
  amd: true
  paths:
  - ./scripts
  exclude:
  - ./scripts/lib

sass:
  syntax: scss
  paths:
  - ./styles
  exclude:
  - ./styles/lib

exclude:
  - assets.json
  - bin
  - demo # scripts/lib/soundmanager/demo
  - doc # scripts/lib/soundmanager/doc
  - Gemfile
  - Gemfile.lock
  - README.md
